# Generated by Django 5.0.4 on 2024-05-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmedia',
            name='file_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
