# Generated by Django 5.0.4 on 2025-08-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_city_subcity_alter_listing_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='admin_status',
            field=models.BooleanField(default=True),
        ),
    ]
