# Generated by Django 5.0.4 on 2026-01-24 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_amenity_listing_amenities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='desc',
            new_name='description',
        ),
    ]
