# Generated by Django 5.0.4 on 2026-01-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_rename_desc_listing_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='description',
            new_name='desc',
        ),
    ]
