"""
Django settings for projectrhm project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from pathlib import Path
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
#BASE_DIR = Path(__file__).resolve().parent.parent

# explicitly point to the .env in project root
load_dotenv(os.path.join(BASE_DIR, ".env"))

print("SUPABASE_URL:", os.environ.get("SUPABASE_URL"))
print("SUPABASE_SEC:", os.environ.get("SUPABASE_SEC"))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG')

#ALLOWED_HOSTS = ['localhost','127.0.0.1','plenty-bikes-judge.loca.lt','yba.onrender.com','10.195.50.131']
ALLOWED_HOSTS = [
    "betnet-mbis.onrender.com",
    "localhost",
    "127.0.0.1",
]

# Application definition

APP_NAME = 'የሚከራይ ቤት አለ'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'tailwind',
    'theme',
    'listing',
    'messaging',
    'corsheaders',
    'fontawesomefree',
    'admindashboard',
    'comment',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

CSRF_TRUSTED_ORIGINS = [
    'https://yba.onrender.com',
    
]


CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://yba.onrender.com"
]




ROOT_URLCONF = 'projectrhm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'projectrhm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

#DATABASES = {
 #   'default': {
  #      'ENGINE': 'django.db.backends.postgresql',
   #     'NAME': 'postgres',
    #    'USER': 'postgres',
     #   'PASSWORD': '#@Betnet123',
      #  'HOST': 'dbqgonxdzatjoxqhrhfw.supabase.co',
       # 'PORT': '6543',
        #'OPTIONS': {
            #'sslmode': 'require',
        #},
    #}
#}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

#DATABASES = {
#    'default': {
 #       'ENGINE': 'django.db.backends.postgresql',
  #      'NAME': 'postgres',
   #     'USER': 'postgres',
    #    'PASSWORD': os.environ.get('#@Betnet123'),
     #   'HOST': 'dbqgonxdzatjoxqhrhfw.supabase.co',
      #  'PORT': '5432',
    #}
#}

# DATABASES = {
 #    'default': {
  #       'ENGINE': os.environ.get("DB_ENGINE"),
   #      'NAME': 'rhmdb',
    #     'USER':'postgres',
     #    'PASSWORD': 'nat@postgress',
      #   'HOST': '127.0.0.1',
       #  'PORT': '5432',
  #   }
 #}



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
AUTH_USER_MODEL = 'users.CustomUser'
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#STATIC_URL = '/static/'
#STATICFILES_DIRS = [BASE_DIR / "static"]  
STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TAILWIND_APP_NAME = 'theme'

NPM_BIN_PATH = 'C:/Users/Tamuq/AppData/Roaming/npm/npm.cmd'

INTERNAL_IPS = [
    "127.0.0.1",
]
