# Generated by Django 5.0.4 on 2024-05-29 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_listing_status'),
        ('messaging', '0002_rename_timestamp_message_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='listing.listing'),
        ),
    ]
