# Generated by Django 5.0.4 on 2026-01-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_conversation_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
