# Generated by Django 5.0.4 on 2026-01-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_message_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
